apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: learn-k8s
  labels:
    app: mongo
spec:
  replicas: 1 # db scaled with stateful-set, not deployment
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo # pod label
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: learn-k8s
spec:
  selector:
    app: mongo # should match pod label
  ports:
    - protocol: TCP
      port: 27017 # any port
      targetPort: 27017 # container port
